# Exploration 6. AI Writer 

## 1. kaggle에서 Song Lyrics 데이터를 다운받고 폴더에 이동시킴

In [1]:
# 터미널에서 작업함

## 2. 데이터 읽어오기

In [2]:
import re                  # 정규표현식을 위한 Regex 지원 모듈 (문장 데이터를 정돈하기 위해) 
import numpy as np         # 변환된 문장 데이터(행렬)을 편하게 처리하기 위해
import tensorflow as tf    # 대망의 텐서플로우!

In [3]:
import glob
import os

txt_file_path = os.getenv('HOME')+'/aiffel/lyricist/data/lyrics/*'

txt_list = glob.glob(txt_file_path)

raw_corpus = []

# 여러개의 txt 파일을 모두 읽어서 raw_corpus 에 담습니다.
for txt_file in txt_list:
    with open(txt_file, "r") as f:
        raw = f.read().splitlines()
        raw_corpus.extend(raw)

print("데이터 크기:", len(raw_corpus))
print("Examples:\n", raw_corpus[:3])

데이터 크기: 187088
Examples:
 ['Now greetings to the world! Standing at this liquor store,', 'Whiskey coming through my pores,', 'Feeling like I run this whole block.']


## 3. 데이터 정제

앞서 배운 테크닉들을 활용해 문장 생성에 적합한 모양새로 데이터를 정제하세요!

preprocess_sentence() 함수를 만든 것을 기억하시죠? 이를 활용해 데이터를 정제하도록 하겠습니다.

추가로 지나치게 긴 문장은 다른 데이터들이 과도한 Padding을 갖게 하므로 제거합니다.  
너무 긴 문장은 노래가사 작사하기에 어울리지 않을수도 있겠죠.
그래서 이번에는 문장을 토큰화 했을 때 토큰의 개수가 15개를 넘어가는 문장을 학습데이터에서 제외하기를 권합니다. 

In [4]:
for idx, sentence in enumerate(raw_corpus):
    if len(sentence) == 0: continue   # 길이가 0인 문장은 건너뜁니다.
    if sentence[-1] == ":": continue  # 문장의 끝이 : 인 문장은 건너뜁니다.

    if idx > 9: break   # 일단 문장 10개만 확인해 볼 겁니다.
        
    print(sentence)

Now greetings to the world! Standing at this liquor store,
Whiskey coming through my pores,
Feeling like I run this whole block.
Lotto tickets cheap beer
That's why you can catch me here,
Tryna scratch my way up to the top. 'Cause my job got me going nowhere,
So I ain't got a thing to lose.
Take me to a place where I don't care,
This is me and my liquor store blues. I'll take one shot for my pain,
One drag for my sorrow.


In [5]:
def preprocess_sentence(sentence):
    sentence = sentence.lower().strip()       # 소문자로 바꾸고 양쪽 공백을 삭제
  
    # 아래 3단계를 거쳐 sentence는 스페이스 1개를 delimeter로 하는 소문자 단어 시퀀스로 바뀝니다.
    sentence = re.sub(r"([?.!,¿])", r" \1 ", sentence)        # 패턴의 특수문자를 만나면 특수문자 양쪽에 공백을 추가
    sentence = re.sub(r'[" "]+', " ", sentence)                  # 공백 패턴을 만나면 스페이스 1개로 치환
    sentence = re.sub(r"[^a-zA-Z?.!,¿]+", " ", sentence)  # a-zA-Z?.!,¿ 패턴을 제외한 모든 문자(공백문자까지도)를 스페이스 1개로 치환

    sentence = sentence.strip()

    sentence = '<start> ' + sentence + ' <end>'      # 이전 스텝에서 본 것처럼 문장 앞뒤로 <start>와 <end>를 단어처럼 붙여 줍니다
    
    return sentence

print(preprocess_sentence("This @_is ;;;sample        sentence."))   # 이 문장이 어떻게 필터링되는지 확인해 보세요.

<start> this is sample sentence . <end>


In [6]:
corpus = []

for sentence in raw_corpus:
    if len(sentence) == 0: continue
    if sentence[-1] == ":14": continue
        
    corpus.append(preprocess_sentence(sentence))
        
corpus[:10]

['<start> now greetings to the world ! standing at this liquor store , <end>',
 '<start> whiskey coming through my pores , <end>',
 '<start> feeling like i run this whole block . <end>',
 '<start> lotto tickets cheap beer <end>',
 '<start> that s why you can catch me here , <end>',
 '<start> tryna scratch my way up to the top . cause my job got me going nowhere , <end>',
 '<start> so i ain t got a thing to lose . <end>',
 '<start> take me to a place where i don t care , <end>',
 '<start> this is me and my liquor store blues . i ll take one shot for my pain , <end>',
 '<start> one drag for my sorrow . <end>']

In [7]:
def tokenize(corpus):
    # 텐서플로우에서 제공하는 Tokenizer 패키지를 생성
    tokenizer = tf.keras.preprocessing.text.Tokenizer(
        num_words=7000,  # 전체 단어의 개수 
        filters=' ',    # 별도로 전처리 로직을 추가할 수 있습니다. 이번에는 사용하지 않겠습니다.
        oov_token="<unk>"  # out-of-vocabulary, 사전에 없었던 단어는 어떤 토큰으로 대체할지
    )
    tokenizer.fit_on_texts(corpus)   # 우리가 구축한 corpus로부터 Tokenizer가 사전을 자동구축하게 됩니다.

    # 이후 tokenizer를 활용하여 모델에 입력할 데이터셋을 구축하게 됩니다.
    tensor = tokenizer.texts_to_sequences(corpus)   # tokenizer는 구축한 사전으로부터 corpus를 해석해 Tensor로 변환합니다.

    # 입력 데이터의 시퀀스 길이를 일정하게 맞추기 위한 padding  메소드를 제공합니다.
    # maxlen의 디폴트값은 None입니다. 이 경우 corpus의 가장 긴 문장을 기준으로 시퀀스 길이가 맞춰집니다.
    tensor = tf.keras.preprocessing.sequence.pad_sequences(tensor, padding='post')  

    print(tensor,tokenizer)
    return tensor, tokenizer

tensor, tokenizer = tokenize(corpus)

[[   2   50 5044 ...    0    0    0]
 [   2 2762  287 ...    0    0    0]
 [   2  329   25 ...    0    0    0]
 ...
 [   2    8   38 ...    0    0    0]
 [   2   39    4 ...    0    0    0]
 [   2    5   90 ...    0    0    0]] <keras_preprocessing.text.Tokenizer object at 0x7f79edefd250>


In [8]:
print(tensor[:3, :10])

[[   2   50 5044   10    6  143   59  581   71   42]
 [   2 2762  287  132   13    1    4    3    0    0]
 [   2  329   25    5  247   42  263  648   20    3]]


In [9]:
for idx in tokenizer.index_word:
    print(idx, ":", tokenizer.index_word[idx])

    if idx >= 10: break

1 : <unk>
2 : <start>
3 : <end>
4 : ,
5 : i
6 : the
7 : you
8 : and
9 : a
10 : to


In [18]:
src_input = tensor[:14, :14]  # tensor에서 마지막 토큰을 잘라내서 소스 문장을 생성합니다. 마지막 토큰은 <end>가 아니라 <pad>일 가능성이 높습니다.
tgt_input = tensor[:14, 1:14]    # tensor에서 <start>를 잘라내서 타겟 문장을 생성합니다.

print(src_input[0])
print(tgt_input[0])

[   2   50 5044   10    6  143   59  581   71   42 1374 1046    4    3]
[  50 5044   10    6  143   59  581   71   42 1374 1046    4    3]


In [11]:
BUFFER_SIZE = len(src_input)
BATCH_SIZE = 256
steps_per_epoch = len(src_input) // BATCH_SIZE

VOCAB_SIZE = tokenizer.num_words + 1    # tokenizer가 구축한 단어사전 내 7000개와, 여기 포함되지 않은 0:<pad>를 포함하여 7001개

dataset = tf.data.Dataset.from_tensor_slices((src_input, tgt_input)).shuffle(BUFFER_SIZE)
dataset = dataset.batch(BATCH_SIZE, drop_remainder=True)
dataset

<BatchDataset shapes: ((256, 346), (256, 346)), types: (tf.int32, tf.int32)>

## 4. 평가 데이터셋 분리

훈련 데이터와 평가 데이터를 분리하세요! 

tokenize() 함수로 데이터를 Tensor로 변환한 후,  
sklearn 모듈의 train_test_split() 함수를 사용해 훈련 데이터와 평가 데이터를 분리하도록 하겠습니다.  
단어장의 크기는 12,000 이상으로 설정하세요!  
총 데이터의 20%를 평가 데이터셋으로 사용해 주세요!

In [12]:
#enc_train, enc_val, dec_train, dec_val = <코드 작성>

In [ ]:
def tokenize(corpus):
    # 텐서플로우에서 제공하는 Tokenizer 패키지를 생성
    tokenizer = tf.keras.preprocessing.text.Tokenizer(
        num_words=2000,  # 전체 단어의 개수 
        filters=' ',    # 별도로 전처리 로직을 추가할 수 있습니다. 이번에는 사용하지 않겠습니다.
        oov_token="<unk>"  # out-of-vocabulary, 사전에 없었던 단어는 어떤 토큰으로 대체할지
    )
    tokenizer.fit_on_texts(corpus)   # 우리가 구축한 corpus로부터 Tokenizer가 사전을 자동구축하게 됩니다.

    # 이후 tokenizer를 활용하여 모델에 입력할 데이터셋을 구축하게 됩니다.
    tensor = tokenizer.texts_to_sequences(corpus)   # tokenizer는 구축한 사전으로부터 corpus를 해석해 Tensor로 변환합니다.

    # 입력 데이터의 시퀀스 길이를 일정하게 맞추기 위한 padding  메소드를 제공합니다.
    # maxlen의 디폴트값은 None입니다. 이 경우 corpus의 가장 긴 문장을 기준으로 시퀀스 길이가 맞춰집니다.
    tensor = tf.keras.preprocessing.sequence.pad_sequences(tensor, padding='post')  

    print(tensor,tokenizer)
    return tensor, tokenizer

tensor, tokenizer = tokenize(corpus)

In [13]:
#print("Source Train:", enc_train.shape)
#print("Target Train:", dec_train.shape)

In [14]:
#out:

#Source Train: (124960, 14)
#Target Train: (124960, 14)

## 5. 인공지능 만들기

모델의 Embedding Size와 Hidden Size를 조절하며 10 Epoch 안에 val_loss 값을 2.2 수준으로 줄일 수 있는 모델을 설계하세요!  
(Loss는 아래 제시된 Loss 함수를 그대로 사용!)

In [6]:
import tensorflow as tf    # 대망의 텐서플로우!
import os

In [ ]:
class TextGenerator(tf.keras.Model):
    def __init__(self, vocab_size, embedding_size, hidden_size):
        super(TextGenerator, self).__init__()
        
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_size)
        self.rnn_1 = tf.keras.layers.LSTM(hidden_size, return_sequences=True)
        self.rnn_2 = tf.keras.layers.LSTM(hidden_size, return_sequences=True)
        self.linear = tf.keras.layers.Dense(vocab_size)
        
    def call(self, x):
        out = self.embedding(x)
        out = self.rnn_1(out)
        out = self.rnn_2(out)
        out = self.linear(out)
        
        return out
    
embedding_size = 256
hidden_size = 1024
model = TextGenerator(tokenizer.num_words + 1, embedding_size , hidden_size)

In [ ]:
for src_sample, tgt_sample in dataset.take(1): break
model(src_sample)

In [ ]:
model.summary()

In [ ]:
optimizer = tf.keras.optimizers.Adam()
loss = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True,
    reduction='none'
)

model.compile(loss=loss, optimizer=optimizer)
model.fit(dataset, epochs=2)

# 프로젝트를 마치며...

팀원들 가사나오는거 보면서 부러웠다. 음.... 나는 회사일과 병행한다는 핑계가 있지만... 
이렇게 제출 당일에 커널이 연결이 안될지는 몰랐다... 새로운 프로젝트에서 gpu를 많이 써서일까? 
갑자기 이렇게 커널 오류로 작동이 안된느 경우는 처음이다. 
커널 연결이 안됩니다.... ㅠㅠ 너무 밤이 늦어서 퍼실님들께 도움을 요청할수가 없을것 같다.. ㅠㅠ 
앞으로 exploration은 밀린것 부터 해야겠다.. 이럴줄 알았으면 오늘 ex안하고 이거 할걸 그랬다.. 

예전 ex에서 sklearn 코드를 가져오긴 했는데, 여기서 접붙여서 사용하기가 어렵다.. 
앞으로는 ai를 하기 위해서는 잘 가져다 쓰고, 바꿔쓰고 해야하는데,, 
이정도도 못하면 안되지 않나.. 하는 자괴감이 든다... ㅠㅠ 
나는 갈수록 과제가 어려워 지는 것 같다. ㅠㅠ! 그래도 제출은 하겠습니다.. ! 